export EDITOR="vim"
export LANG=en_US.UTF-8

bindkey "^B" history-beginning-search-backward

# dont use oh-my-zsh auto complete
unsetopt correct_all

setopt autopushd

# Comment this out to disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

# this is a great place to store local settings like $PATH
[[ -f ~/.bash_profile ]] && . ~/.bash_profile

# place per machine/user settings here
[[ -f ~/.zshrc.local ]] && . ~/.zshrc.local

# for the lulz
alias hack="cat /dev/urandom | hexdump"

unsetopt correct_all

# override lukerandall theme function
function my_git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null)
  if [[ $ref == refs* ]]; then
    git="${ref#refs/heads/}"
  elif [[ -n $(git describe --exact-match HEAD 2> /dev/null) ]]; then
    git=$(git describe --exact-match HEAD 2> /dev/null)
  elif [[ -n $(git describe HEAD 2> /dev/null) ]]; then
    git=$(git describe HEAD | sed "s/.\{9\}$//g" | sed "s/-/+/"  2> /dev/null)
  fi

  GIT_STATUS=$(git_prompt_status)
  [[ -n $GIT_STATUS ]] && GIT_STATUS=" $GIT_STATUS"

  if [[ $git =~ .+ ]]; then
    echo "$ZSH_THEME_GIT_PROMPT_PREFIX$git$GIT_STATUS$ZSH_THEME_GIT_PROMPT_SUFFIX";
  fi
}

# Less Colors for Man Pages
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

if hash git-setup-user 2>/dev/null; then
  git-setup-user
fi
